SQLite3_Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SQLite3_Blog/article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
	path('article-list/', views.article_list, name = 'article_list'),
	path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
	path('article-create/', views.article_create, name='article_create'),
	path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
	path('article-update/<int:id>/', views.article_update, name='article_update'),
]

SQLite3_Blog/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 已有代码，处理一级回复
    path('post-comment/<int:article_id>', views.post_comment, name='post_comment'),
    # 新增代码，处理二级回复
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

SQLite3_Blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

SQLite3_Blog/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager




class ArticleColumn(models.Model):
    title = models.CharField(max_length=100, blank=True)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title




class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)
    tags = TaggableManager(blank = True)


    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

SQLite3_Blog/article/forms.py
from django import forms
# 引入文章模型
from .models import ArticlePost

# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body', 'tags')

SQLite3_Blog/article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import ArticlePost
from .models import ArticleColumn
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm
import markdown


def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # 初始化查询集
    article_list = ArticlePost.objects.all()

    # 搜索查询集
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

    # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    paginator = Paginator(article_list, 10)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 需要传递给模板（templates）的对象
    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
    }

    return render(request, 'article/list.html', context)



def article_detail(request, id):
    article = ArticlePost.objects.get(id = id)
    article.total_views += 1
    article.save(update_fields=['total_views'])
    comments = Comment.objects.filter(article=id)
    comment_form = CommentForm()
    md = markdown.Markdown(
        extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)
    context = { 'article':article, 'toc': md.toc, 'comments': comments, 'comment_form': comment_form}
    return render(request, 'article/detail.html', context)



@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                # 保存文章栏目
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            return HttpResponse("The content of the form is incorrect. Please re-fill it.")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = { 'article_post_form': article_post_form, 'columns': columns }
        return render(request, 'article/create.html', context)



@login_required(login_url='/userprofile/login/')
def article_delete(request, id):
    article = ArticlePost.objects.get(id=id)
    article.delete()
    return redirect("article:article_list")




@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("Sorry, you have no right to modify this article.")
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            if request.POST['column'] != 'none':
                # 保存文章栏目
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None
            article.save()
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("The content of the form is incorrect. Please re-fill it.")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = { 'article': article, 'article_post_form': article_post_form, 'columns': columns }
        return render(request, 'article/update.html', context)

SQLite3_Blog/templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}


                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">Article Title</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>


                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="column">Column</label>
                    <select class="form-control" 
                            id="column" 
                            name="column"
                            >
                            <option value="none">Please select a column:</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>


                <!-- 文章标签 -->
                <div class="form-group">
                    <label for="tags">Label</label>
                    <input type="text"
                           class="form-control col-3"
                           id="tags"
                           name="tags"
                    >
                </div>


                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">Article Body</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>


                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">Finish</button>


            </form>
        </div>
    </div>
</div>
{% endblock content %}

SQLite3_Blog/templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
Article details
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                    Author：{{ article.author }}
                    {% if user == article.author %}
                        · <a href="#" onclick="confirm_delete()">Delete article</a>
                        · <a href="{% url "article:article_update" article.id %}">
                            Edit article
                        </a>
                    {% endif %}
                </div>
                <div>
                    Pageviews：{{ article.total_views }}
                </div>
            </div>
            <!-- 文章正文 -->
            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>


            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form 
                        action="{% url 'comment:post_comment' article.id %}" 
                        method="POST"
                    >
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    Comment：
                                </strong>
                            </label>
                            <div>
                                {{ comment_form.media }}
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary ">Submit</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    Please <a href="{% url 'userprofile:login' %}"> login </a> then reply
                </h5>
                <br>
            {% endif %}
            


            <!-- 显示评论 -->
            {% load mptt_tags %}
            <h4>A total of {{ comments.count }} comments</h4>
            <div class="row">
                <!-- 遍历树形结构 -->
                {% recursetree comments %}
                    {% with comment=node %}
                        <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif %}"
                            id="comment_elem_{{ comment.id }}" 
                        >
                            <hr>
                            <p>
                                <strong style="color: pink">
                                    {{ comment.user }}
                                </strong> 

                                <!-- 显示被回复人 -->
                                {% if comment.reply_to %}
                                    <i class="far fa-arrow-alt-circle-right" 
                                       style="color: cornflowerblue;"
                                    ></i>
                                    <strong style="color: pink">
                                        {{ comment.reply_to }}
                                    </strong> 
                                {% endif %}

                            </p>
                            <div>{{ comment.body|safe }}</div>

                            <div>
                                <span style="color: gray">
                                    {{ comment.created|date:"Y-m-d H:i" }}
                                </span>

                                <!-- 加载 modal 的按钮 -->
                                {% if user.is_authenticated %}
                                    <button type="button" 
                                            class="btn btn-light btn-sm text-muted" 
                                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                    >
                                        Reply
                                    </button>
                                {% else %}
                                    <a class="btn btn-light btn-sm text-muted" 
                                        href="{% url 'userprofile:login' %}"
                                    >
                                        Reply
                                    </a>
                                {% endif %}
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" 
                                 id="comment_{{ comment.id }}" 
                                 tabindex="-1" 
                                 role="dialog" 
                                 aria-labelledby="CommentModalCenter" 
                                 aria-hidden="true"
                            >
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content" style="height: 480px">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Reply {{ comment.user }}：</h5>
                                        </div>
                                        <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                    </div>
                                </div>
                            </div>

                            {% if not comment.is_leaf_node %}
                                <div class="children">
                                    {{ children }}
                                </div>
                            {% endif %}
                        </div>
                        
                    {% endwith %}
                {% endrecursetree %}
            </div>  
        </div>

        <!-- 目录 -->
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>Catalogue</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 粘性侧边栏样式 -->
<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0); /* For browsers don't support translate3d. */
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "Confirm deletion",
            // 正文
            content: "Are you sure to delete this article?",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }
</script>
{% endblock content %}

{% block script %}
<!-- 粘性侧边栏 -->
<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>

<!-- Ckeditor自适应 -->
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>

<!-- 新增代码，唤醒二级回复的 modal -->
<script>
    // 加载 modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' + 
                article_id + 
                '/' + 
                comment_id + 
                '"' + 
                ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' + 
                comment_id + 
                '"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    }



</script>
{% endblock script %}

SQLite3_Blog/templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    Home
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">

    <!-- 面包屑导航 -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?search={{ search }}&column={{ column }}&tag={{ tag }}">
                    Newest
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}&column={{ column }}&tag={{ tag }}">
                    Hottest
                </a>
            </li>
        </ol>
    </nav>


    <!-- 新增，搜索栏 -->
    <div class="row">
        <div class="col-auto mr-auto">
            <form class="form-inline" >
                <label class="sr-only">content</label>
                <input type="text" 
                    class="form-control mb-2 mr-sm-2" 
                    name="search" 
                    placeholder="Search for articles..." 
                    required
                >
            </form>
        </div>
    </div>


    <!-- 新增，搜索提示语 -->
    {% if search %}
        {% if articles %}
            <h4>The search results of the game are as follows <span style="color: red">"{{ search }}"</span> are as follows:</h4>
            <hr>        
        {% else %}
            <h4>No related articles for <span style="color: red">"{{ search }}"</span> </h4>
            <hr>
        {% endif %}
    {% endif %}


    <!-- 列表循环 -->
    <div class="row mt-2">
        {% for article in articles %}



            <!-- 文章内容 -->
            <div class="col-12">
                <!-- 栏目 -->
               {% if article.column %}
                    <button type="button" 
                        class="btn btn-sm mb-2
                            {% if article.column.title == 'Python' %}
                                btn-success
                            {% elif article.column.title == 'JAVA' %}
                                btn-danger
                            {% elif article.column.title == 'HTML' %}
                                btn-warning
                            {% endif %}
                        "
                    >
                        {{ article.column }}
                    </button>
                {% endif %}

                <!-- 标签 -->
                <span>
                    {% for tag in article.tags.all %}
                        <a href="{% url 'article:article_list' %}?tag={{ tag }}"
                           class="badge badge-secondary" 
                        >
                            {{ tag }}
                        </a>
                    {% endfor %}
                </span>



                <!-- 标题 -->
                <h4>
                    <b>
                        <a name="article_title" href="{% url 'article:article_detail' article.id %}"
                           style="color: black;" 
                        >
                            {{ article.title }}
                        </a>
                    </b>
                </h4>
                <!-- 摘要 -->
                <div>
                    <p style="color: gray;">
                    {{ article.body|slice:'100' }}...
                    </p>
                </div>
                <!-- 注脚 -->
                <p>
                    <!-- 附加信息，增加了图标 -->
                    <span>
                        <i class="fas fa-eye" style="color: lightskyblue;"></i>
                        {{ article.total_views }}&nbsp;&nbsp;&nbsp;
                    </span>
                    <span>
                        <i class="fas fa-comments" style="color: yellowgreen;"></i>
                        <!-- 修改为评论的计数 -->
                        {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
                    </span>
                    <span>
                        <i class="fas fa-clock" style="color: pink;"></i>
                        {{ article.created|date:'Y-m-d' }}
                    </span>
                </p>
                <hr>
            </div>
        {% endfor %}
    </div>


    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}&tag={{ tag }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}&tag={{ tag }}" 
                       class="btn btn-secondary"
                    >
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                    <a name="next_page" href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}&tag={{ tag }}" class="btn btn-secondary">
                    {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}&tag={{ tag }}" class="btn btn-success">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>


</div>





{% endblock content %}

SQLite3_Blog/templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} Update Article {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Article Title</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>

                
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="column">Column</label>
                    <select class="form-control" 
                            id="column" 
                            name="column"
                            >
                            <option value="none">Please select a column:</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                {% if column.id == article.column.id %}
                                    selected
                                {% endif %}
                                >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>



                <div class="form-group">
                    <label for="body">Article Body</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Finish</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}