SQLite3_Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('password-reset/', include('password_reset.urls')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SQLite3_Blog/article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
	path('article-list/', views.article_list, name = 'article_list'),
	path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
	path('article-create/', views.article_create, name='article_create'),
	path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
	path('article-update/<int:id>/', views.article_update, name='article_update'),
]

SQLite3_Blog/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

SQLite3_Blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

SQLite3_Blog/templates/back_to_top_func.html
<!-- Author: 鹦鹉 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: white;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

SQLite3_Blog/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" 
          href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" 
          crossorigin="anonymous"
    >
</head>

<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}

    <div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>

    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'popper/popper.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>    
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block script %}{% endblock script %}
    {% include 'back_to_top_func.html' %}

    <!-- 增加样式 -->
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
            margin-bottom: -40px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>



</body>

</html>

SQLite3_Blog/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">Max &copy; Wux37@cardiff.ac.uk 2019</p>
    </div>
</footer>

SQLite3_Blog/templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="{% url 'article:article_list' %}">My Blog</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}">Article</a>
        </li>
        {% if user.is_authenticated %}

        <!-- 如果用户已经登录，则显示用户名下拉框 -->
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if unread_count %}
                    <svg viewBox="0 0 8 8"
                         width="8px"
                         height="8px">
                        <circle cx="4"
                                cy="4"
                                r="4"
                                fill="#ff6b6b"
                        ></circle>
                    </svg>
                {% endif %}
                {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url "notice:list" %}">Notic
                    {% if unread_count %}
                    <span class="badge badge-danger">{{ unread_count }}</span>
                    {% endif %}
                </a>
                <a class="dropdown-item" href="{% url 'article:article_create' %}">Write article</a>
                <a class="dropdown-item" href="{% url 'userprofile:logout' %}">Logout</a>
                <a class="dropdown-item" href="#" onclick="user_delete()">Delete users</a>
                <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>Information</a>
              </div>
          </li>
        <!-- 如果用户未登录，则显示 “登录” -->
        {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'userprofile:login' %}">Login</a>
          </li>                    
        <!-- if 语句在这里结束 -->
        {% endif %}
      </ul>
    </div>
  </div>
</nav>


{% if user.is_authenticated %}
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "Confirm deletion",
                content: "Confirm delete user profile?",
                btn: ["Yes", "No"],
                yes: function(index, layero) {
                    location.href='{% url "userprofile:delete" user.id %}'
                },
            })
        }
    </script>
{% endif %}